{"name": "登录异常，测试数据是：{'accounts': '', 'pwd': 'yaoyao1', 'exp': '登录账号有误'}", "status": "passed", "parameters": [{"name": "args", "value": "{'accounts': '', 'pwd': 'yaoyao1', 'exp': '登录账号有误'}"}], "start": 1599776155679, "stop": 1599776155987, "uuid": "4fbb2ef4-24d8-4d65-8d05-adad004a83c5", "historyId": "ff1d27090ef74452512974d50f385b0f", "testCaseId": "acfd50c72596b11b4392c40d7652bccf", "fullName": "script.test_login.TestLogin#test_login_error", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-NM1TAU0"}, {"name": "thread", "value": "223692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}