{"name": "登录异常，测试数据是：{'accounts': '', 'pwd': 'yaoyao1', 'exp': '登录账号有误'}", "status": "passed", "parameters": [{"name": "args", "value": "{'accounts': '', 'pwd': 'yaoyao1', 'exp': '登录账号有误'}"}], "start": 1599763942437, "stop": 1599763942581, "uuid": "90767d58-b6cf-4fc1-8a7a-9d3668f2faeb", "historyId": "ff1d27090ef74452512974d50f385b0f", "testCaseId": "acfd50c72596b11b4392c40d7652bccf", "fullName": "script.test_login.TestLogin#test_login_error", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-NM1TAU0"}, {"name": "thread", "value": "190340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}